---
Name: qr-code-generator
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - XD\QRCodeGenerator\Extensions\SiteConfigExtension
SilverStripe\Control\Director:
  rules:
    'qr/$ID': XD\QRCodeGenerator\Controllers\QRCodeController
#SilverStripe\CMS\Model\SiteTree:
#  extensions:
#    - XD\QRCodeGenerator\Extensions\SiteTreeExtension

